on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: false
        type: string
  workflow_call:
    inputs:
      version:
        required: true
        type: string

name: Publish image to GHCR

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
      id-token: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get current date
        id: date
        run: echo "date=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
      
      - name: Parse version
        id: parse
        run: |
          VERSION="${{ inputs.version }}"
          
          if [ -z "$VERSION" ]; then
            echo "No version provided, using timestamp tags only"
            echo "use_version=false" >> $GITHUB_OUTPUT
          else
            VERSION=${VERSION#v}
            IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
            
            echo "use_version=true" >> $GITHUB_OUTPUT
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "major=$MAJOR" >> $GITHUB_OUTPUT
            echo "minor=$MINOR" >> $GITHUB_OUTPUT
            
            echo "Parsed version: v$VERSION (major: $MAJOR, minor: $MINOR, patch: $PATCH)"
          fi

      - name: Append build timestamp to source
        run: |
          echo 'console.log("Built on: '$(date -u +%Y-%m-%dT%H:%M:%SZ)'");' >> src/index.ts

      - name: Build and push (with version)
        if: steps.parse.outputs.use_version == 'true'
        uses: docker/build-push-action@v4
        with:
          platforms: linux/arm64, linux/amd64
          push: true
          tags: |
            ghcr.io/coffee-cup/railway-utils:latest
            ghcr.io/coffee-cup/railway-utils:v${{ steps.parse.outputs.version }}
            ghcr.io/coffee-cup/railway-utils:v${{ steps.parse.outputs.major }}
            ghcr.io/coffee-cup/railway-utils:v${{ steps.parse.outputs.major }}.${{ steps.parse.outputs.minor }}
            ghcr.io/coffee-cup/railway-utils:${{ steps.date.outputs.date }}
            
      - name: Build and push (timestamp only)
        if: steps.parse.outputs.use_version == 'false'
        uses: docker/build-push-action@v4
        with:
          platforms: linux/arm64, linux/amd64
          push: true
          tags: |
            ghcr.io/coffee-cup/railway-utils:latest
            ghcr.io/coffee-cup/railway-utils:${{ steps.date.outputs.date }}
