on:
  workflow_dispatch:

name: Publish image to GHCR

jobs:
  debian:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
      id-token: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install Nixpacks
        run: curl -sSL https://nixpacks.com/install.sh | bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%s)"

      # - name: Build with Nixpacks
      #   id: nixpacks
      #   run: nixpacks build . --platform linux/amd64 --platform linux/arm64 --name railway-utils

      - name: Build
        run: |
          docker buildx build . --platform=linux/arm64,linux/amd64 -t railway-utils
          docker tag railway-utils ghcr.io/railway-utils:latest

      - name: Push
        run: docker push ghcr.io/railway-utils:latest
      
      # - name: Build
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: base/debian
      #     platforms: linux/arm64, linux/amd64, linux/386
      #     push: ${{ github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
      #     tags: ghcr.io/coffee-cup/railway-utils:latest, ghcr.io/railway-utils:${{ steps.date.outputs.date }}
